<?php 

/**
 * Implements hook_user_login();
 * 
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

function hello_drupal8_user_login($account){
    /* Call hook_user_login dynamicly and Redirect to home page '<front>' when user log in*/
    // Redirect to an existing route
    $url = Url::fromRoute('<front>');
    // Redirect to internal node
    $url = Url::fromUserInput('/node/3');
    $new_url = new RedirectResponse($url->toString());
    $new_url->send();
}